osx_image: xcode9
language: objective-c
script:
  - |
    xcodebuild test \
    -project LTMorphingLabelDemo.xcodeproj \
    -scheme LTMorphingLabelDemo \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' \
    | xcpretty
